apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: calci
  name: calci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calci
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: calci
    spec:
      containers:
      - image: harish7587/calci:latest
        name: calci
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: my-cluster
spec:
  type: ClusterIP
  selector:
    app: calci
  ports:
    - port: 80
      targetPort: 3000
  externalIPs:
    - 192.168.49.2    
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress

spec:
  rules:
  - host: "calci-app.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: calci
            port:
              number: 3000
